spring:
  datasource:
    url: jdbc:mariadb://ec2-3-129-195-197.us-east-2.compute.amazonaws.com/KSY
    username: ksy
    password: ksy1010%%
    driver-class-name: org.mariadb.jdbc.Driver

#  security:
#    user:
#      name: user1
#      password: 1111
#      roles: USER

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

server:
  port: 80

mybatis:
  type-aliases-package: com.example.board.vo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
