spring:
  datasource:
    url: jdbc:mariadb://ec2-3-129-195-197.us-east-2.compute.amazonaws.com/KSY
    username: ksy
    password: ksy1010%%
    driver-class-name: org.mariadb.jdbc.Driver

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

server:
  port: 8085

mybatis:
  type-aliases-package: com.example.board.vo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
